In [32]:
import numpy as np
array=np.arange(1,21)
print("array: ",array)
print("array shape: ", array.shape)
print("min and max of the array: ",array.min(),"and",max(array))
print("mean & standard deviation of the array:", array.mean(),"and",array.std())
array1=array.reshape(4,5)
print("reshaped array (4*5) : ", array1)
print("second row of the matrix: ", array1[1])
print("third row of the matrix: ",array1[2])

array:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
array shape:  (20,)
min and max of the array:  1 and 20
mean & standard deviation of the array: 10.5 and 5.766281297335398
reshaped array (4*5) :  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
second row of the matrix:  [ 6  7  8  9 10]
third row of the matrix:  [11 12 13 14 15]


In [42]:
import numpy as np
A = np.array([10, 20, 30, 40, 50])
B = np.array([5, 10, 15, 20, 25])
print("addition:", A+B)
print("Substraction:", A-B)
print("Multiplication:", A*B)
print("Divison:", A/B)
print("Sum of all elements in A: ", np.sum(A))

addition: [15 30 45 60 75]
Substraction: [ 5 10 15 20 25]
Multiplication: [  50  200  450  800 1250]
Divison: [2. 2. 2. 2. 2.]
Sum of all elements in A:  150


In [44]:
import pandas as pd
data = {
    "Roll No": [101, 102, 103, 104, 105],
    "Name": ["Ravi", "Priya", "Kiran", "Anu", "Sita"],
    "Marks": [85, 92, 78, 88, 95]
}
df = pd.DataFrame(data)
print("data frame:\n", df)
print("\nFirst Three Records:")
print(df.head(3))
average = df["Marks"].mean()
print("\nAverage Marks:", average)
highest = df.loc[df["Marks"].idxmax()]
print("\nStudent with Highest Marks:",highest)
lowest = df.loc[df["Marks"].idxmin()]
print("\nStudent with Lowest Marks:",lowest)
grades = []
for mark in df["Marks"]:
    if mark >= 90:
        grades.append("A")
    elif mark >= 80:
        grades.append("B")
    else:
        grades.append("C")
df["Grade"] = grades
print("\nDataFrame with Grade:")
print(df)

data frame:
    Roll No   Name  Marks
0      101   Ravi     85
1      102  Priya     92
2      103  Kiran     78
3      104    Anu     88
4      105   Sita     95

First Three Records:
   Roll No   Name  Marks
0      101   Ravi     85
1      102  Priya     92
2      103  Kiran     78

Average Marks: 87.6

Student with Highest Marks: Roll No     105
Name       Sita
Marks        95
Name: 4, dtype: object

Student with Lowest Marks: Roll No      103
Name       Kiran
Marks         78
Name: 2, dtype: object

DataFrame with Grade:
   Roll No   Name  Marks Grade
0      101   Ravi     85     B
1      102  Priya     92     A
2      103  Kiran     78     C
3      104    Anu     88     B
4      105   Sita     95     A


In [45]:
import pandas as pd
df = pd.DataFrame({
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor"],
    "Price": [50000, 500, 1200, 10000],
    "Quantity": [10, 50, 30, 15]
})
df["Total Value"] = df["Price"] * df["Quantity"]
print(df)
print("\nHighest Total Value:")
print(df.loc[df["Total Value"].idxmax()])
print("\nOverall Inventory Value:", df["Total Value"].sum())

    Product  Price  Quantity  Total Value
0    Laptop  50000        10       500000
1     Mouse    500        50        25000
2  Keyboard   1200        30        36000
3   Monitor  10000        15       150000

Highest Total Value:
Product        Laptop
Price           50000
Quantity           10
Total Value    500000
Name: 0, dtype: object

Overall Inventory Value: 711000


In [49]:
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df["Species"] = iris.target
print(df)
print(df.head(5))
print(df.shape)
print(df.columns)
print(df.isnull().sum())
print(df.describe())
print(df["Species"].value_counts())

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     Species  
0          0